---
build_from:
  aarch64: arm64v8/debian:13.0-slim
  amd64: amd64/debian:13.0-slim
  armhf: arm32v5/debian:13.0-slim
  armv7: arm32v7/debian:13.0-slim
  i386: i386/debian:13.0-slim
codenotary:
  signer: codenotary@frenck.dev
