---
build_from:
  aarch64: arm64v8/debian:12.6-slim
  amd64: amd64/debian:12.6-slim
  armhf: arm32v5/debian:12.6-slim
  armv7: arm32v7/debian:12.6-slim
  i386: i386/debian:12.6-slim
codenotary:
  signer: codenotary@frenck.dev
